M48
; DRILL file {KiCad 7.0.6} date Tue 18 Jul 2023 09:57:43 AM CDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-18T09:57:43-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0472
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0591
%
G90
G05
T1
X3.65Y-3.3
X3.65Y-3.85
T2
X3.8Y-3.3
X3.8Y-3.6
X3.9Y-3.3
X3.9Y-3.6
X4.0Y-3.3
X4.0Y-3.6
X4.1Y-3.3
X4.1Y-3.6
X4.4Y-3.6
X4.5Y-3.6
X4.6Y-3.6
T3
X3.9Y-3.0
X4.0Y-3.0
X4.1Y-3.0
T4
X3.3Y-4.0
X3.5Y-4.0
X3.7Y-4.0
X3.9Y-4.0
X4.1Y-4.0
T0
M30
